### PR TITLE
HOCS-2403-Mock date in tests

### PR DESCRIPTION
**Pull request by agraham19**
CS-2403-Internal Bug: DateInput Component sets maxYear to current date + 100 years breaking tests every year
 
  * mock date in tests so snapshot tests don't break
  * modify component to evaluate date during creation, rather than on import

### CODE REVIEW

**Comment by parth-ho** [comment]
Shouldn't there be a snapshot to go with the test changes?

**Comment by agraham19** [comment]
> Shouldn't there be snapshot changes to go with the test changes?

Because I've mocked the date to 2019, it still produces 2119, so the snapshot does not need to change.

**Comment by parth-ho** [comment]
Within the snapshot file there should be a snapshot for each test case where you use `toMatchSnapshot`, since there's a new test case: `should render when maxYear is passed` the snapshot file will also have been updated. If you run `npm test` on this branch you should see that the new test snapshot has been added to the existing snapshot file.

**Comment by agraham19** [comment]
> Within the snapshot file there should be a snapshot for each test case where you use `toMatchSnapshot`, since there's a new test case: `should render when maxYear is passed` the snapshot file will also have been updated. If you run `npm test` on this branch you should see that the new test snapshot has been added to the existing snapshot file.

Ah. Sorry, I've added it now.

**Review by parth-ho — APPROVED** [review]
Looks good! The `jest-date-mock` package will defo come in handy for future date related tests, as testing code that handles dates can be a bit tricky.

**Pull request merged**
