### PR TITLE
Epic/hocs 2710 form validation main merge

### PR DESCRIPTION
**Pull request by Paulcr-ho**
Main branch merge into HOCS-COMP epic.

### CODE REVIEW

**Comment by Paulcr-ho** [comment]
server/lists/adapters/case-view-all-stages.js had merge conflicts. Whichever version we choose, the build fails. @LiamMacP is looking into it.

**Comment by LiamMacP** [comment]
> server/lists/adapters/case-view-all-stages.js had merge conflicts. Whichever version we choose, the build fails. @LiamMacP is looking into it.

Merge issue has been rectified 😄

**Review by robertdeniszczyc2 — APPROVED** [review]
Looks OK to me

**Review by agraham19 — APPROVED** [review]

**Review by LiamMacP — APPROVED** [review]

**Review by SeanReedHomeOffice — COMMENTED** [review]
LGTM

**Pull request merged**
