### PR TITLE
HOCS-4598: remove unnecessary call and update display of Active stage…

### PR DESCRIPTION
**Pull request by gary-newbolt**
… title when no stages exist

### CODE REVIEW

**Review by LiamMacP — COMMENTED** [review]
Does this have any tests/ need any?

**Comment by gary-newbolt** [comment]
I probably should add one in to be fair... I'll sort add one in shortly. Thanks @LiamMacP

**Review by abarker66 — DISMISSED** [review]
Discussed, tested, LGTM.

**Comment by gary-newbolt** [comment]
unit test added in, also includes fix for deep copy issue on other tests in the script.

**Review by abarker66 — APPROVED** [review]
re-reviewed, looks good.

**Pull request merged**
